require "rake/testtask"

directories = ["./.", "./data_list", "./student", "./students_list", "./sql", "./gui"]

desc "Запускаем тесты"
Rake::TestTask.new(:test) do |t|
	t.libs << directories
	t.test_files = FileList['tests/**/test_*.rb']
end

desc "Генерируем конкретный UML"
task :uml,[:uml_path] do |t, args|
	plant_uml_path = "/mnt/c/plantuml/plantuml.jar"
	
	system "java -Djava.awt.headless=true -DPLANTUML_LIMIT_SIZE=8192 -jar #{plant_uml_path} -charset \"UTF-8\" #{args[:uml_path]}"
end

desc "Генерируем все UML"
task :all_uml do
	Dir["./uml/*.txt"].each do |file|
		Rake::Task[:uml].execute(uml_path: file)
		puts "#{file} done"
	end
end


desc "Запускаем main.rb"
task :run do |t|
	dir_string = directories.map{|s| "-I#{s}"}.join(" ")
	
	system "ruby #{dir_string} main.rb"
end

desc "Проверяем работу sql"
task :sql_test do |t|
	dir_string = directories.map{|s| "-I#{s}"}.join(" ")
	
	system "ruby #{dir_string} sql_test.rb"
end